#! /bin/sh

export MY_FOLDER=/home/canus
export SCR_PATH=$MY_FOLDER/Scripts
#### AUTOSTART ####
sxhkd &
picom &
nitrogen --restore &
#/usr/bin/feh --randomize --bg-fill "/home/contre/Pictures/Wallpapers/random/3" &
clipmenud &
~/.screenlayout/widescreen.sh &
bluetoothctl power on &
setxkbmap -layout us -variant mac &
nvidia-settings -a "[gpu:0]/GPUFanControlState=1" -a "[fan:0]/GPUTargetFanSpeed=10" -a "[fan:1]/GPUTargetFanSpeed=10"

#### MONITORS ####
bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-4 -d 6 7 8 9 ﭮ    

#### BSPWM custom layout | https://github.com/phenax/bsp-layout
bsp-layout set even

#### BSPWM rules ####
bspc rule -a TelegramDesktop desktop=''
bspc rule -a Whatsapp desktop=''
bspc rule -a discord desktop='ﭮ'
bspc rule -a Music desktop=''
bspc rule -a Gmail desktop=''
bspc rule -a Pavucontrol:pavucontrol state=floating center=true rectangle=1000x600+0+0
bspc rule -a Alacrity:Alacrity center=true rectangle=1200x600+0+0
bspc rule -a burp-StartBurp:burp-StartBurp state=floating
bspc rule -a Dropdown state=floating layer=above rectangle=1899x500+750+180 monitor=HDMI-0
bspc rule -a "*:*:Picture-in-Picture" state=floating rectangle=600x400+0+0 center=true

#### BSPWM configuration ####

bspc config window_gap 10
bspc config border_width 1
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 20
bspc config split_ratio 0.50
bspc config click_to_focus true
bspc config gapless_monocle true
bspc config pointer_action1 move
bspc config single_monocle false
#$SCR_PATH/bspwm-scr/borders.sh &
bspc config -m HDMI-0 top_padding 0
bspc config -m DP-4 top_padding 0
bspc config pointer_modifier mod4
bspc config focus_by_distance true
bspc config borderless_monocle true
bspc config history_aware_focus true
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 40
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#### BSPWM coloring ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

### Lemonbar bar (be sure to load bspwm monitors first)
pkill -x lemonbar
python3 "$HOME/.config/lemonbar/bar.py" &
bspc subscribe node_state | while read _ _ _ _ state flag; do
	if [[ $state == fullscreen ]]; then
		if [[ $flag == on ]]; then
			xdo lower -N Bar
		else
			xdo raise -N Bar
		fi
	fi
done &
