#! /bin/sh

bspc rule -r "*" # Remove any pre-existing rule 

export MY_FOLDER=/home/server
export SCR_PATH=$MY_FOLDER/Scripts
#### AUTOSTART ####
sxhkd &
picom &
#/usr/bin/feh --randomize --bg-fill "/home/contre/Pictures/Wallpapers/random/3" &
clipmenud &
autorandr --load tv &
nitrogen --restore &
bluetoothctl power on &
setxkbmap -layout us -variant mac &
nvidia-settings -a "[gpu:0]/GPUFanControlState=1" -a "[fan:0]/GPUTargetFanSpeed=10" -a "[fan:1]/GPUTargetFanSpeed=10"

#### MONITORS ####
bspc monitor DP3 -d 1 2 3 4 5

#### BSPWM custom layout | https://github.com/phenax/bsp-layout
bsp-layout set even

#### BSPWM rules ####
bspc rule -a TelegramDesktop desktop=''
bspc rule -a Slack desktop=''
bspc rule -a discord desktop='ﭮ'
bspc rule -a Music desktop=''
#bspc rule -a Gmail desktop=''
bspc rule -a Pavucontrol:pavucontrol state=floating center=true rectangle=1000x600+0+0
bspc rule -a Dropdown state=floating layer=above rectangle=1800x500+65+20 monitor=DP3 sticky=on
bspc rule -a "*:*:Picture-in-Picture" state=floating rectangle=600x400+0+0 center=true


#### BSPWM configuration ####

bspc config window_gap 0
bspc config border_width 2
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config split_ratio 0.50
bspc config click_to_focus true
bspc config gapless_monocle false
bspc config pointer_action1 move
bspc config directional_focus_tightness low
bspc config single_monocle false
#$SCR_PATH/bspwm-scr/borders.sh &
bspc config -m DP3 top_padding 0
bspc config -m DP-4 top_padding 0
bspc config pointer_modifier mod4
bspc config focus_by_distance true
bspc config borderless_monocle true
bspc config history_aware_focus true
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 13
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#### BSPWM coloring ####
bspc config focused_border_color        "#737373"
bspc config normal_border_color         "#242427"
bspc config active_border_color         "#242427"

### Lemonbar bar (be sure to load bspwm monitors first)
polybar &
