# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix") ];


  # Variables
  environment.sessionVariables = rec {
    MYENV = "notebook";
    MY_FOLDER = "/home/canus";
    SCR_PATH = "/home/canus/Scripts";
  };

  environment.variables = {
    MYENV = "notebook";
    MY_FOLDER = "/home/canus";
    SCR_PATH = "/home/canus/Scripts";
  };
  # Hardware

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4e62ee06-b5ed-4c1a-aa07-147ce5fa566d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-722be326-e3d4-4f05-b2a1-ad34b9d76aa3".device = "/dev/disk/by-uuid/722be326-e3d4-4f05-b2a1-ad34b9d76aa3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DCAC-2CC4";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/6d66ce4b-d593-4591-9caf-6d6f2cd94b3b"; }
    ];

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  boot.initrd.luks.devices."luks-34fe280a-5ab1-4f6e-8de7-b5d58e524452".device = "/dev/disk/by-uuid/34fe280a-5ab1-4f6e-8de7-b5d58e524452";

}
