#! /bin/sh
#  ____ _____ 
# |  _ \_   _|  Derek Taylor (DistroTube)
# | | | || |  	http://www.youtube.com/c/DistroTube
# | |_| || |  	http://www.gitlab.com/dwt1/ 
# |____/ |_|  	
#        
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

export MY_FOLDER=/home/canus
export SCR_PATH=$MY_FOLDER/Scripts
#### AUTOSTART ####
sxhkd &
picom &
nitrogen --restore &
clipmenud &
setxkbmap -layout us -variant mac &
#nvidia-settings -a "[gpu:0]/GPUFanControlState=1" -a "[fan:0]/GPUTargetFanSpeed=50" -a "[fan:1]/GPUTargetFanSpeed=50"

### Status bar
pkill -x lemonbar
python3 "$HOME/.config/lemonbar/bar.py" &
bspc subscribe node_state | while read _ _ _ _ state flag; do
	if [[ $state == fullscreen ]]; then
		if [[ $flag == on ]]; then
			xdo lower -N Bar
		else
			xdo raise -N Bar
		fi
	fi
done &
#~/.config/polybar/launch.sh &
#~/.config/lemonbar/lemonbar.sh &

#### MONITORS ####
bspc monitor DP-4 -d 1 2 3 4 5 
bspc monitor DP-0 -d 6 7 8 9:Msg

#### BSPWM configuration ####
bspc config border_width                  2
bspc config window_gap                    10
bspc config -m DP-0 top_padding           0
bspc config -m DP-4 top_padding           0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config pointer_motion_interval       40
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-4)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-0)

