local g = vim.g -- Global variables
local opt = vim.opt -- Set options (global/buffer/windows-scoped)

opt.ch = 0
opt.showmatch = true
opt.swapfile = false
opt.mouse = 'a'
opt.termguicolors = true
opt.tabstop = 4
opt.number = true
opt.foldlevel = 99
opt.laststatus = 3
opt.shiftwidth = 2
opt.spelllang = 'en'
opt.wrap = false
opt.virtualedit = 'onemore'
opt.wildmenu = true
opt.spell = false
opt.smarttab = true
opt.hlsearch = true
opt.numberwidth = 2
opt.expandtab = true
opt.selection = 'exclusive'
opt.incsearch = true
opt.showmode = false
opt.updatetime = 300
opt.autoindent = true
opt.ignorecase = true
opt.splitbelow = true
opt.splitright = true
opt.cursorline = false
opt.smartindent = true
--opt.foldmethod = "expr"
opt.signcolumn = "yes:1"
opt.relativenumber = true
opt.fileencoding = 'utf-8'
opt.fillchars='eob: '
--opt.foldexpr = "nvim_treesitter#foldexpr()"
