import = [ "~/.config/alacritty/colors-material.toml" ]
# program = "/bin/zsh"
# tabspaces = 4
live_config_reload = true
colors.draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9

  [window.padding]
  x = 3
  y = 3

# [class]
# instance = "Alacritty"
# general = "Alacritty"

[scrolling]
history = 10_000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
blink_interval = 500
unfocused_hollow = true
thickness = 0.15

  [cursor.style]
  shape = "Beam"
  blinking = "Always"

[font]
size = 11

  [font.normal]
  family = "JetBrainsMono NF"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono NF"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono NF"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono NF"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[mouse]
hide_when_typing = true
