local opt = vim.opt -- Set options (global/buffer/windows-scoped)
opt.ch = 0
opt.mouse = "a"
opt.tabstop = 4
opt.wrap = false
opt.number = true
opt.spell = false
opt.foldlevel = 99
opt.shiftwidth = 2
opt.hlsearch = true
opt.numberwidth = 2
opt.smarttab = true
opt.wildmenu = true
opt.autochdir = false
opt.expandtab = true
opt.incsearch = true
opt.showmatch = true
opt.showmode = false
opt.spelllang = "en"
opt.swapfile = false
opt.updatetime = 300
opt.autoindent = true
opt.ignorecase = true
-- opt.laststatus = 3
opt.modifiable = true
opt.splitbelow = true
opt.splitright = true
opt.cursorline = false
opt.smartindent = true
opt.fillchars = "eob: "
opt.signcolumn = "yes:1"
opt.termguicolors = true
--opt.foldmethod = "expr"
opt.relativenumber = true
opt.fileencoding = "utf-8"
opt.selection = "exclusive"
opt.virtualedit = "onemore"
--vim.g.rasmus_bold_keywords = true
--opt.foldexpr = "nvim_treesitter#foldexpr()"
vim.g.clipboard = {
    name = 'osc52',
    copy = {
        ["+"] = {'osc52'},
        ["*"] = {'osc52'},
    },
    paste = {
        ["+"] = {'pbpaste'},
        ["*"] = {'pbpaste'},
    },
    cache_enabled = 1,
}
